# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80d73c5a0a834e0f5cbdfe999aa05b9772ea329fed816009149b1d01ad23f17377842bb936e1a77d1c21651c6b1669170e75166809af0e77eb942eb84a7e2fb

test:
  secret_key_base: 6c52a43bcfab206593b7ab8cd520d016adb53224f59989ce844225b13095d73a8a7decac31d65b5d9b9b6256ff6655849ba44cf75c1efa94f36c8e8780eaf563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
